FROM python:3.12-slim

WORKDIR /app

# Copier et installer les dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code source de l'API et de l'entraînement
COPY mlops/ ./mlops/

# Exposition du port
EXPOSE 8000

# Commande de démarrage
CMD ["uvicorn", "mlops.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
